# This workflow will do a clean install of node dependencies, build the source code and deploy to an FTP server.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ftp.danting.ca
          user: ${{ secrets.FTP_RESUME_USER }}
          password: ${{ secrets.FTP_RESUME_PASSWORD }}
          localDir: 'dist'
          remoteDir: '.'
